export const ROUTES = {
    pendingApplications: '/pendingApplications',
    affiliateManagement: '/affiliateManagement',
    releaseManagement: '/releaseManagement',
    archiveReleases: '/archiveReleases',
    usageReportsReview: '/usageReportsReview',
    reports: '/usageReportsReview',
    memberManagement: '/memberManagement',
    postAnnouncement: '/postAnnouncement',
    ihtsdoReleases: '/ihtsdoReleases',
    fileDownloadReport: '/fileDownloadReport',
    activityLog: '/activityLog',
    importAffiliates: '/importAffiliates',
    manageBlocklist: '/blocklist',
    nationalRegistrationList: '/country',
    metrics: '/metrics',
    systemLoggers: '/logs',
    userDashboard: '/userDashboard',
    register: '/register',
    emailVerification: '/emailVerification',
    landingPage: '/',
    login: '/login',
    applicationReview : '/applicationReview',
    
  };